name: test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i && npm run lint

  unit:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: install deps
        run: npm i && npx lerna bootstrap --no-ci

      - name: install e2e deps && build
        run: npm i --prefix test/e2e/example && npm run build:mini:cross --prefix test/e2e/example

      - name: exec unit test
        run: npm t
