name: test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i --legacy-peer-deps && npm run lint

  unit:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: install deps
        run: npm i --legacy-peer-deps && npm i --prefix packages/api-proxy --legacy-peer-deps && npm i --prefix test/e2e/miniprogram-project --legacy-peer-deps && npx lerna bootstrap --no-ci

      - name: build
        run: npm run copyPlugin --prefix test/e2e/miniprogram-project && npm run build:cross --prefix test/e2e/miniprogram-project

      - name: exec unit test
        run: npm t && npm t --prefix test/e2e/miniprogram-project
